include:
  - local: /gitlab-ci/config/00--common--rules.yml
  - local: /gitlab-ci/config/00--common--images.yml

stages:             # Files from the given stage should be prefixed with:
  - automation          # temp
  - init                # 10--
  - test                # 20--
  - deploy              # only required for gitlab pages (job "pages" needs to be in "deploy" stage)
  - cargo-build         # 30--
  - cargo-test          # 40--
  - guest-os-build      # 46--
  - guest-os-test       # 47--
  - host-os-build       # 52--
  - build-determinism-test  # 55--
  - prod-tests          # 60--
    # Shard prod tests into 5 groups, because there are 5 'cdnightly' testnet environments.
    # The stages are purely for visual convenience when rendering the pipeline in the GitLab UI.
  - prod-tests-01
  - prod-tests-02
  - prod-tests-03
  - prod-tests-04
  - prod-tests-05
  - benchmark-tests
  - benchmark-spot-tests
  - sns-tests
  - push-branches       # 75--
  - npm-release         # 80--
  - finalize            # 100--

default:
  # Retry config copied from:
  # https://gitlab.com/gitlab-org/gitlab/blob/master/.gitlab/ci/global.gitlab-ci.yml#L1-9
  # Complete description available at:
  # https://docs.gitlab.com/ee/ci/yaml/#retry
  retry:
    max: 2  # This is confusing but this means "3 runs at max".
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure

variables:
  TEST_ES_HOSTNAMES: >-
    elasticsearch-node-0.testnet.dfinity.systems:443,
    elasticsearch-node-1.testnet.dfinity.systems:443,
    elasticsearch-node-2.testnet.dfinity.systems:443
  CI_PRE_CLONE_SCRIPT: |
    # This script caches the git repo on the host.

    # MacOS note: the gitlab runner will ignore this var on MacOS since config does not have
    # pre_clone_script set in the runner config

    echo -e "\e[0Ksection_start:$(date +%s):pre_clone_script[collapsed=true]\r\e[0KClick here to see the pre_clone_script"
    set -eExuo pipefail

    GIT_CACHE_PATH="/cache/git-v3/@{CI_PROJECT_PATH}/@{CI_CONCURRENT_ID}"
    mkdir -p "@{GIT_CACHE_PATH}"

    JOB_ID_FILE="@{GIT_CACHE_PATH}/CI_JOB_ID.bak"
    touch "@{JOB_ID_FILE}"
    if [ "$(cat @{JOB_ID_FILE})" == "@{CI_JOB_ID}" ]; then
        RETRY_DELAY=@(( RANDOM % 60 + 60))
        echo "Sleeping @{RETRY_DELAY} second(s) before retry ..."
        sleep "@{RETRY_DELAY}"
    fi
    trap 'echo -n "@{CI_JOB_ID}" > "@{JOB_ID_FILE}"' EXIT

    export GIT_TRACE=1
    export GIT_CURL_VERBOSE=1
    git config --global --add safe.directory "@{GIT_CACHE_PATH}"
    pushd "@{GIT_CACHE_PATH}"
    
    # Step 1. Seed the repo if it doesn't exit or has been corrupted.
    # On CI we've observed partial downloads of the repo [e.g. missing .git dir]
    if ! git fsck; then
      echo "Cloning fresh git repository"
      find . -mindepth 1 -delete
      time git clone --depth=500 "@{CI_REPOSITORY_URL}" .
    fi

    # Step 2. Fetch the commit sha into the cache.
    # CI_REPOSITORY_URL contains the CI_JOB_TOKEN.
    # The cached one will have come from a previous job, and thus its token
    # is invalid. So just update the token.
    git remote set-url origin "@{CI_REPOSITORY_URL}"

    # Fetch the target commit sha into the cache.
    # If this fails, for example if the repo has become corrupted, then wipe
    # the cache and perform a fresh clone.
    if ! time git fetch origin "@{CI_COMMIT_SHA}"; then
      echo "Git fetch into local cached failed. Making a clean git clone"
      find . -mindepth 1 -delete
      time git clone --depth=500 "@{CI_REPOSITORY_URL}" .
    fi
    popd

    # Step 3. Clone a fresh working repo from the cache.

    # This directory should not exist unless something changed on GitLab,
    # or someone has bind mounted it from the runner. To be safe just delete it.
    rm -fr "@{CI_PROJECT_DIR}"
    mkdir -p "@{CI_PROJECT_DIR}"

    pushd "@{CI_PROJECT_DIR}"
    time git clone "@{GIT_CACHE_PATH}" .
    git checkout "@{CI_COMMIT_SHA}"
    git remote set-url origin "@{CI_REPOSITORY_URL}"
    popd

before_script:
  - |
    # Execute the before_script section
    echo -e "\e[0Ksection_end:$(date +%s):before_script\r\e[0K"  # first close before_script section, if open

    # Start the (collapsed) before_script section
    set -eExuo pipefail
    echo -e "\e[0Ksection_start:$(date +%s):before_script[collapsed=true]\r\e[0KClick here to see the before_script section"

    date +%s > "/tmp/job_start_date_${CI_JOB_ID:-}"
    # date -Iseconds is not supported by BSD date (macOS)
    date +"%Y-%m-%dT%H:%M:%S%z" > "/tmp/job_start_iso_date_${CI_JOB_ID:-}"
    date
    command -v ssh-agent > /dev/null
    test -z "${SSH_AUTH_SOCK:-}" && { eval "$(ssh-agent -s)"; ssh-add - <<< "${SSH_PRIVATE_KEY}"; }
    mkdir -p ~/.ssh
    chmod 0700 ~/.ssh

    echo -e "Host *\nUser gitlab-runner\n" > ~/.ssh/config
    date

    export ROOT_PIPELINE_ID=${PARENT_PIPELINE_ID:-$CI_PIPELINE_ID}

    if [ "${CI_DISPOSABLE_ENVIRONMENT:-false}" != "true" ]; then
      # MacOS + shell builds
      export CARGO_TARGET_DIR="$CI_PROJECT_DIR/target"
    else
    # GitLab may not preserve some file permissions that are chowned in the pre clone script.
    # And the files will all be owned by root.
    # Some commands care about the permissions of the configs they use. For example, Ansible will refuse
    # to use a cfg file that a different user owns.
      sudo chown ubuntu:ubuntu -R "${CI_PROJECT_DIR}"
      sudo find "${CI_PROJECT_DIR}" -type d -exec chmod 0755 '{}' \;
    fi

    # seed the /srv/nix directory on k8s hosts
    if [ -e /etc/nix/nix.conf ] && [ ! -e /home/ubuntu/.nix-profile ] && [[ "$CI_RUNNER_TAGS" =~ "k8s" ]]; then
      echo "sandbox = false" | sudo tee -a /etc/nix/nix.conf
      /usr/bin/nix-install
      sudo sed -i '/sandbox/d' /etc/nix/nix.conf
    fi

    # set all git dirs safe
    git config --global --add safe.directory '*'

    # docker login for RO to overcome anonymous pull limit of 100 pulls / 6h
    # enterprise logged in account has 5000 pulls / 24h
    if [ "$(uname)" == "Linux" ]; then
      docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD_RO"
    fi

  - echo -e "\e[0Ksection_end:$(date +%s):before_script\r\e[0K"


# TESTING NOTE:
# $SHELL_WRAPPER allows us to emulate CI runs without actually executing the complicated and
#                time-consuming operations.
#                In normal execution, "$SHELL_WRAPPER" will be substituted with "/usr/bin/time"
#                In CI validation, "$SHELL_WRAPPER" will be substituted with "echo"

after_script:
  - |
    # Start the after_script section
    echo -e "\e[0Ksection_start:$(date +%s):after_script[collapsed=true]\r\e[0KClick here to see the after_script section. It does not affect the job success status"

    # Export all the environmental variables so that the GITLAB configured variables are available to after_script.sh
    export ROOT_PIPELINE_ID=${PARENT_PIPELINE_ID:-$CI_PIPELINE_ID}
    buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" after-script -- "${CI_PROJECT_DIR}"/gitlab-ci/src/after_script/after_script.sh

    # Finish and collapse the after_script section
    echo -e "\e[0Ksection_end:$(date +%s):after_script\r\e[0K"

.build-env-base:
  # Generally only the last push to a branch matters and older jobs can be cancelled
  # https://docs.gitlab.com/ee/ci/yaml/#interruptible
  # Jobs can override this by setting `interruptible: false`
  interruptible: true
  artifacts:
    paths:
      - "junit_data/*"
      - "coredumps/*.txt"
      - "coredumps/*.gz"
    when: always
  variables:
    GET_SOURCES_ATTEMPTS: 5
    GIT_DEPTH: 0  # Pull the complete repo initially
    GIT_STRATEGY: "fetch"  # And then pull only new commits
    SHELL_WRAPPER: "/usr/bin/time"

.nix-build-env-base:
  extends:
    - .cargo-rules
    - .build-env-base
  variables:
    BUILD_COMMAND_PRE: ""
    BUILD_COMMAND: "echo Replace this with a build command"
    BUILD_COMMAND_POST: ""
  script:
    - |
      set -eExuo pipefail
      cd "${CI_PROJECT_DIR}/rs"

      bash -c "$BUILD_COMMAND_PRE"

      # failures will contain a counter of failed commands
      # this way nix-shell will exit with non-zero value if any of the commands fails in it
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" nix-shell -- \
      "$SHELL_WRAPPER" nix-shell --run "
        set -eExuo pipefail

        buildevents cmd \"$ROOT_PIPELINE_ID\" \"$CI_JOB_ID\" build-command -- \
        bash -c \"set -eExuo pipefail; $BUILD_COMMAND\"

        echo \"$BUILD_COMMAND_POST\"
        bash -c \"$BUILD_COMMAND_POST\"
        set +x
      "

.ubuntu-docker:
  extends: 
    - .build-env-base
    - .ic-build-image
  tags:
    - dfinity
    - docker
    - ubuntu

.ubuntu-docker-k8s:
  extends:
    - .build-env-base
    - .ic-build-image
  tags:
    # distribute jobs between docker and k8s runners
    - dfinity
    - ubuntu

# docker & k8s
.bazel-build-k8s:
  extends:
    - .ubuntu-docker-k8s
    # Replace with below bazel image once gen cargo pipeline is purged.
    - .ic-build-image
    # - .ic-build-bazel-image
  tags:
    - dfinity
    - ubuntu
    # Run in ZH since BuildFarm is in ZH
    - zh
  variables:
    BAZEL_STARTUP_ARGS: "--output_base=/cache/bazel-output/${CI_CONCURRENT_ID}"
    BAZEL_EXTRA_ARGS: "--repository_cache=/cache/bazel"
    BAZEL_CI_CONFIG: "--config=ci"

.ubuntu-nix-docker:
  extends:
    - .nix-build-env-base
    - .ubuntu-docker
    - .ic-build-nix-image
  # Here is how docker builds work:
  # - The $CI_COMMIT_SHA is checked out at: /builds/dfinity/ic
  # - The repo is built with $BUILD_COMMAND
  # - Build results are stored in non-persisted /cargo_target
  # - The container is destroyed and all non-persisted data is dropped, including /cargo_target
  variables:
    # This MUST match the directory used in our `docker-build-ic` script
    RUSTFLAGS: "--remap-path-prefix=${CI_PROJECT_DIR}=/ic"

.ubuntu-nix-docker-k8s:
  extends: .ubuntu-nix-docker
  tags:
    # distribute jobs between docker and k8s runners
    - dfinity
    - ubuntu

.ubuntu-nix-docker-pinned-dc:
  extends: .ubuntu-nix-docker
  tags:
    # We dynamically set tags to pin jobs to one DC
    - $SELECTED_DC # 'zh', 'sf' or 'ch'
    - dfinity
    - ubuntu
    - docker

.ubuntu-nix-docker-k8s-pinned-dc:
  extends: .ubuntu-nix-docker
  tags:
    # We dynamically set tags to
    # - pin jobs to one DC
    # - distribute jobs between docker and k8s runners
    - $SELECTED_DC # 'zh', 'sf' or 'ch'
    - dfinity
    - ubuntu

.macos-nix-native:
  extends:
     - .nix-build-env-base
  tags:
    - dfinity
    - macos
