check-bins-linux:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: cargo-test
  needs:
    - job: wait-for-bazel-test-all
      artifacts: false
  image:
    # 21.04
    name: ubuntu@sha256:b5a61709a9a44284d88fb12e5c48db0409cfad5b69d4ff8224077c57302df9cf
  before_script: /bin/true
  after_script: /bin/true
  variables:
    ARTIFACT_PREFIX: sdk-release/x86_64-linux
  script:
    - |
      set -exuo pipefail

      apt-get update && apt-get install --yes --no-install-recommends curl ca-certificates

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/replica.gz" | gunzip > /tmp/replica
      chmod +x /tmp/replica
      ldd /tmp/replica
      /tmp/replica --print-sample-config --replica-version 1 >/dev/null

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/ic-starter.gz" | gunzip > /tmp/ic-starter
      chmod +x /tmp/ic-starter
      ldd /tmp/ic-starter
      /tmp/ic-starter --version

check-bins-darwin:
  extends:
    - .rules-parent-pipeline
  stage: cargo-test
  needs:
    - job: wait-for-bazel-test-all
      artifacts: false
  tags:
    - dfinity
    - macos
  before_script: /usr/bin/true
  after_script: /usr/bin/true
  variables:
    ARTIFACT_PREFIX: sdk-release/x86_64-darwin
    # https://curl.se/mail/lib-2020-06/0010.html
    CURL_SSL_BACKEND: secure-transport
  script:
    - |
      set -exuo pipefail

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/replica.gz" | gunzip > /tmp/replica
      chmod +x /tmp/replica
      otool -L /tmp/replica
      /tmp/replica --print-sample-config --replica-version 1 >/dev/null

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/ic-starter.gz" | gunzip > /tmp/ic-starter
      chmod +x /tmp/ic-starter
      otool -L /tmp/ic-starter
      /tmp/ic-starter --version
